### ISSUE TITLE
Add information about longest digest cycle

### ISSUE THREAD

**Issue by vtakov** [kentcdodds/ng-stats#11]
Currently there is digestLength which shows the current digest length, but in most cases we're looking for the longest digest cycle. For example, it is longer when we load a page for a first time and this time is critical when we have a page with lot of information.

**Comment by kentcdodds** [comment]
I just updated the api. Take a look at the README for the `logDigest` and `trackDigest` options. Should cover your use case I think. Close this if you think so.

**Comment by vtakov** [comment]
Great! Thank you very much!
