### ISSUE TITLE
Template for AngularStats

### ISSUE THREAD

**Issue by vtakov** [kentcdodds/ng-stats#12]
Add template for the stats element, or use css class instead of style attribute.
For example many people use z-index: 9999 for things that have to be on top. And when this happen the stats div element disappear behind them.

**Comment by kentcdodds** [comment]
Good point... I'm actually thinking of making the chart a little better using chart.js or something.

Note, until this is resolved, you could look at some of the logging or tracking options.

**Comment by kentcdodds** [comment]
This is fixed in the most recent version of ng-stats: 2.1.0 bfe586d2c92287edf70dffc1fea48a9d0357f4e2
