### ISSUE TITLE
WARNING: Tried to load angular more than once.

### ISSUE THREAD

**Issue by npearson72** [kentcdodds/ng-stats#13]
First of all, thank you for this library!

I'm getting this message after installing though. Any ideas?

**Comment by kentcdodds** [comment]
Not certain why you would be getting that message. ng-stats doesn't bundle angular and it doesn't attempt to require it. ng-stats depends on angular being on window. Are you using browserify or webpack or something?

**Comment by npearson72** [comment]
I'm using browser-sync, which seems to be using require() calls. But I've not seen the message until I added ng-stats.

**Comment by kentcdodds** [comment]
I've never used browser-sync before. But I can't imagine what it could possibly be. Try removing ng-stats from your dependencies, then copy and paste [the code](https://raw.githubusercontent.com/kentcdodds/ng-stats/master/dist/ng-stats.js) in the browser console and see if you get the same errors.

**Comment by npearson72** [comment]
Seems I have two angular packages in my bower_components.

One is `angular` and the other is `angularjs`

When I tried to uninstall `angular` it complained that all my libraries depend on it. When I tried to uninstall `angularjs` I get this:

`bower conflict      ng-stats depends on angularjs`

**Comment by kentcdodds** [comment]
Ah, interesting. So I guess when I last updated the dependencies for ng-stats, angular was registered as `angularjs`. I'll try to get to fixing this issue as soon as I'm able. Thanks!

**Comment by npearson72** [comment]
Any chance you can change your bower dependencies to use `angular` instead of `angularjs`?

**Comment by npearson72** [comment]
Cool, thank you!

**Comment by kentcdodds** [comment]
This is fixed in the most recent version of ng-stats: 2.1.0 bfe586d2c92287edf70dffc1fea48a9d0357f4e2

**Comment by npearson72** [comment]
Hmm, strange. Getting bower install conflicts around the angular version. You dropped it down to ~1.2.x?

For some reason the `dis` folder never gets generated on a clean install. I've cleared bower cache also.

**Comment by kentcdodds** [comment]
Sorry, I made a mistake. It's fixed now :-) 2.1.1 033cbd29dbd940be9a9458523c151c81b0d968e3

**Comment by npearson72** [comment]
Still no `dis` directory. Am I doing something wrong.

I noticed that this line in your grunt file is new since 2.0.4 (when the `dis` dir was getting generated)

`{expand: true, cwd: 'src', src: ['ng-stats.js'], dest: 'dist/', filter: 'isFile'},`

Otherwise, the angular dependency issue has cleared up ;-)

**Comment by kentcdodds** [comment]
I'm not certain I know what you mean about the `dis` directory. I believe it's always been `dist` and the `main` in the `bower.json` is pointing to `dist/ng-stats.js` so you should be good with that too...

**Comment by npearson72** [comment]
Oops, typo. I meant `dist` -- it's not being generated on my end :-\

**Comment by npearson72** [comment]
Oops, typo. I meant `dist` -- it's not being generated on my end :-\

**Comment by kentcdodds** [comment]
You're right. I feel like a dork. It's now been fixed in 2.1.2... 65ad18dc3434848a9c050695d580eb00549e547c

**Comment by npearson72** [comment]
Haha, no worries. Glad you got it straightened out. I really like this library a lot!

**Comment by npearson72** [comment]
Oh, just one more thing. Can you tag the release ;-)

**Comment by kentcdodds** [comment]
Dah! I just can't win today. Thanks for your patience.

**Comment by kentcdodds** [comment]
Done.

**Comment by npearson72** [comment]
Thank you for helping. Much appreciate it!
