### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by piernik** [kentcdodds/ng-stats#14]
Why new version on bower You need angular 1.2? Everything worked with angular 1.3

**Comment by kentcdodds** [comment]
Sorry about that. I meant to set it to <=1.2.x. This is now fixed in `2.1.1` 033cbd29dbd940be9a9458523c151c81b0d968e3

**Comment by kentcdodds** [comment]
There was a bug in 2.1.1. Please use 2.1.2
