### ISSUE TITLE
are you sure about watches number?

### ISSUE THREAD

**Issue by jiin** [kentcdodds/ng-stats#16]
Hi,

please see http://www.bitlanders.com/ and try to watch the watchers with ng-stats, with two or three infinity page scrolling call ng-stats show > 3k watchers.
Is this number right?

**Comment by kentcdodds** [comment]
I haven't looked at it yet, but I've gotten pages to show over 15k watchers
without even trying hard.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by jiin** [comment]
Angular.js wrote "You should never need more that 2k watcher", but bitlanders remain fluid and fast with 15k watchers

**Comment by kentcdodds** [comment]
I'm not sure where you read that, but either way it's simply not true. I hope that ng-stats helps you work through any issues you've got with performance :D
