### ISSUE TITLE
ng-stats 1-click bookmarklet

### ISSUE THREAD

**Issue by TravisTX** [kentcdodds/ng-stats#17]
Awesome tool.  I think it makes a lot of sense as a 1-click browser bookmarklet, so I made one.

Here it is using the current version of ng-stats: https://gist.github.com/TravisTX/9329a3e8ce969a500360

To add a bookmarklet in Chrome: right click the bookmarks bar, and choose "Add Page".  For the URL, paste in the bookmarklet code.

It's pretty easy to make the bookmarklet code.  If you want to put this into your grunt process, the content of the bookmarklet is just as follows:
javascript: {{contents of ng-stats.min.js}} showAngularStats({position: 'bottomright'});

Hope this helps!

**Comment by kentcdodds** [comment]
That's awesome. I'll look into adding this. Thanks!

-Kent C. Dodds

**Comment by kentcdodds** [comment]
Sorry I haven't gotten around to this yet. I'd be open to a PR though!

**Comment by SomeKittens** [comment]
Alternatively, you could dynamically load the latest `ng-stats.js` from this repo via something like:

    (function() {
      var a = document.createElement("script");
      a.src = "https://rawgithub.com/kentcdodds/ng-stats/master/src/ng-stats.js", document.head.appendChild(a)
    })();

**Comment by kentcdodds** [comment]
OOoooohh, I like that even more! That's something we could just add to the readme :-) Thanks @SomeKittens!

**Comment by SomeKittens** [comment]
@kentcdodds my $0.02 is to create a chrome extension.  Everything's much simpler.

**Comment by kentcdodds** [comment]
Good point... If only I had time for that :-( Would love it if someone else made one though!

**Comment by kentcdodds** [comment]
Added to the readme. Thanks for the contributions! I wish I had time for a Chrome extension :-(
