### ISSUE TITLE
Create a better graph

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/ng-stats#18]
Now that you can add your own listener for the digest cycle and watch count, it would be cool to use ChartJS or D3 to create a better graph to display the data.

**Comment by rev087** [comment]
Wouldn't depending on a third party library introduce a potential conflict if the application you're showing stats for uses a different version of that same library?

**Comment by kentcdodds** [comment]
Hadn't thought of that. Good point. Since I'm planning on merging this into batarang, I think we may go a different direction anyway. Perhaps we'd show the graph in the developer tools...

**Comment by rev087** [comment]
Do you plan on maintaining a functional standalone version for ng-stats? I'd like to implement it in [ng-inspector](https://github.com/rev087/ng-inspector) with your permission. We haven't decided yet what to do eventually with batarang/ng-inspector

**Comment by kentcdodds** [comment]
I do plan on retiring deprecating ng-stats when it's implemented in
batarang. You're more than welcome to implement it in ng-inspector :D

-Kent C. Dodds

**Comment by rev087** [comment]
Do you plan on maintaining a functional standalone version for ng-stats? I'd like to implement it in [ng-inspector](https://github.com/rev087/ng-inspector) with your permission.

We haven't decided yet what to do eventually with batarang/ng-inspector (the goal is to eventually merge them) but moving towards a common base is a good first step.

**Comment by kentcdodds** [comment]
I do plan on retiring deprecating ng-stats when it's implemented in batarang. You're more than welcome to implement it in ng-inspector :D

**Comment by SomeKittens** [comment]
This is twice as tricky as it's being implemented into `ng-hint` which is to be used in CI, etc.  The smartest move may be to put the core `ng-stats` functionality into an `ng-hint` module and have a separate module for consuming the data produced by `ng-stats-core` and displaying a graph.

This way, Batarang could display a graph in DevTools, inspect could place it on the page - everyone gets flexibility.

**Comment by kentcdodds** [comment]
:+1: I like that approach.

**Comment by rev087** [comment]
I like that solution a lot +1
