### ISSUE TITLE
Graph resetting to upper left when calling showAngularStats(false)

### ISSUE THREAD

**Issue by sstorie** [kentcdodds/ng-stats#21]
I'm hoping there's not something obvious I'm doing wrong, but I am using ng-stats with the latest Angular 1.4 branch, and have a simple service to help me enable/disable ng-stats:

    .factory('nx.statistics', [
        function() {

        	var service = {
        		statisticsEnabled: false,
        		toggleStatistics: _toggleStatistics
        	};

        	return service;

            function _toggleStatistics() {
                service.statisticsEnabled = !service.statisticsEnabled;

                if (service.statisticsEnabled === true) {
                	// Enable stats and display the graph in the bottom right
                	//
                    showAngularStats({
                        'position': 'bottomright',
                        'digestTimeThreshold': 16,
                        'autoload': false,
                        'logDigest': true,
                        'logWatches': true
                    });
                } else {
                	// This should hide the window (but stats will continue to collect)
                	//
                    showAngularStats(false);
                }
            }
        }
    ]);

This works as I am expecting, where when the app bootstraps no stats are collected. Then when I toggle them on, the graph appears in the bottom right of the window and works fine. However, when I then toggle the stats off, the graph just jumps to the upper left of the window instead of being removed.

Is there something I'm missing here to remove the graph from the screen after I've displayed it at least once?

**Comment by kentcdodds** [comment]
Very interesting. I don't have time to look at this now. I'll try to get to it as soon as possible. Is there a chance you could look into it and discover how that bug is happening?

**Comment by sstorie** [comment]
Sure thing. The issue is that I installed this via bower, and that gave me the 2.1.3 version instead of the latest version available (2.1.4). The bug was fixed by this commit after 2.1.3 was released:

https://github.com/kentcdodds/ng-stats/commit/dad241f468b98b9b79ff2da9f1f54f7fbc57feb8

...so I'll fix my local install to leverage 2.1.4, but it'd be nice to be able to just use bower to manage this.

**Comment by kentcdodds** [comment]
If I run `$ bower info ng-stats` it shows the latest version is 2.1.4... Make sure that your bower.json isn't enforcing a specific version (you should have it as something like: `~2.1.0` or something like that

**Comment by sstorie** [comment]
Sorry, I misspoke when I implied the latest version wasn't available. I just installed this earlier this morning, but I needed to update my local install just now to pull in the latest version. Sorry for the confusion!

**Comment by kentcdodds** [comment]
Glad it's working! :D Thanks!
