### ISSUE TITLE
Not loading in chrome packaged apps

### ISSUE THREAD

**Issue by SAnDAnGE** [kentcdodds/ng-stats#31]
When using ng-stats in a chrome packaged app, I get the following:
![2015-06-10_22-47-59](https://cloud.githubusercontent.com/assets/2596509/8092507/d568d286-0fc2-11e5-8316-df133d8043dc.png)

**Comment by kentcdodds** [comment]
Looks like chrome packaged apps can't use local/session storage... I think that we could just add a check somewhere around [here](https://github.com/kentcdodds/ng-stats/blob/master/src/ng-stats.js#L55) and skip on the local/session storage stuff in that case. Mind submitting a PR?

**Comment by SomeKittens** [comment]
@SAnDAnGE If I were you, I'd fork the project to shift the `localStorage` stuff to [`chrome.storage.local`](https://developer.chrome.com/extensions/storage).

**Comment by SomeKittens** [comment]
(again, this is Kent's repo, so it's ultimately down to him)

**Comment by SomeKittens** [comment]
(deleted comments, didn't see the PR.  :+1:'s all around)
