### ISSUE TITLE
Bad format of bower.jason

### ISSUE THREAD

**Issue by jmcpeak** [kentcdodds/ng-stats#36]
This line:
"angular": "^1.2.x || >= 1.4.0-beta.0 || >= 1.5.0-beta.0"

Produces this error in "bower-art install":
bower angular#^1.2.x || >= 1.4.0-beta.0 || >= 1.5.0-beta.0         response Unexpected end of input

**Comment by kentcdodds** [comment]
That works fine with angular. What do I need to change to make it work with bower?

**Comment by jmcpeak** [comment]
Good question :)

Not sure - I'll figure it out and get back to you

**Comment by jmcpeak** [comment]
So I read the docs at https://github.com/npm/node-semver#ranges and I found the online tool that lets you test your setting - http://semver.npmjs.com/.

I put in angular in the package field and put in your range selector - ^1.2.x || >= 1.4.0-beta.0 || >= 1.5.0-beta.0.

The format looks fine - closing the issue.
