### ISSUE TITLE
Support Isolate Scope

### ISSUE THREAD

**Issue by daniellmb** [kentcdodds/ng-stats#37]
ng-stats blows up when there are only isolate scopes on the page. We can simply modify the query selector to include isolate scopes.

```js
document.querySelector('.ng-scope, .ng-isolate-scope');
```

**Comment by kentcdodds** [comment]
I think that should be fine. Feel free to make a PR :-)

**Comment by daniellmb** [comment]
Great, will do...

**Comment by kentcdodds** [comment]
Released in `2.3.2`. Thanks!
