### ISSUE TITLE
WARNING: Tried to load angular more than once.

### ISSUE THREAD

**Issue by digital-synapse** [kentcdodds/ng-stats#45]
we are using JSPM. When loading ng-stats v 2.5.0 getting WARNING: Tried to load angular more than once. stack trace comes back to line 7 in ng-stats.js.

```javascript
		module.exports = factory(require("angular"));
```

**Comment by kentcdodds** [comment]
This is because:

> this issue is due to jspm not supporting arbitrary range operators which is actually resulting in a fork of Angular.

- @guybedford [comment](https://github.com/jspm/registry/pull/396#issuecomment-106371511)

With angular-formly, [this](https://github.com/formly-js/angular-formly/commit/c7b253c944c62ffd801561c76b9b1c66680e6251) is what we had to do. Could you make a PR for that?

**Comment by robertbaker** [comment]
fixed in #47

**Comment by robertbaker** [comment]
@kentcdodds 

Still throwing the same issue with 2.5.1

**Comment by kentcdodds** [comment]
Hmmm... @guybedford, do you have any ideas?

**Comment by guybedford** [comment]
@robertbaker do you know how this fork is coming about? Do you get multiple versions for `jspm inspect github:angular/bower-angular` or `jspm inspect npm:angular` here? If you can share those outputs that would likely explain how the version mismatch is happening.

**Comment by robertbaker** [comment]
```
c:\git\pos>jspm inspect github:angular/bower-angular
     Updating registry cache...

     Installed versions of github:angular/bower-angular

       angular 1.4.5 (^1.4)

       github:angular-ui/ui-router@0.2.15
         angular 1.4.5 (^1.3.2)

       github:angular/bower-angular-animate@1.4.5
         angular 1.4.5 (^1.3.0)

       github:angular/bower-angular-aria@1.4.5
         angular 1.4.5 (^1.3.0)

       github:angular/bower-angular-mocks@1.4.5
         angular 1.4.5 (^1.3.0)

       github:angular/bower-material@master
         angular 1.4.5 (^1.3.15)


c:\git\pos>jspm inspect npm:angular

     Installed versions of npm:angular

       npm:ng-click-select@0.1.5
         angular 1.4.5 (^1.0.0)

       npm:ng-stats@2.5.1
         angular 1.4.5 (*)
```

**Comment by guybedford** [comment]
@robertbaker thanks so much for the update - ok so the issue here is we need to pick Angular from npm OR github, but having both is causing conflicts. Which do you think is best the npm source or github source? This is somewhat of a conflict we need to resolve for everyone actually, I've created https://github.com/jspm/jspm-cli/issues/1132 to track this further.

**Comment by guybedford** [comment]
(note updating your config dependencies manually within `npm:ng-click-select@0.1.5` and `npm:ng-stats@2.5.1` to use `github:angular/bower-angular@1.4.5` would resolve the fork)

**Comment by robertbaker** [comment]
@guybedford I think the npm version is ideal. I typically only use github for when I want to use the master branch or when it's not on npm.
