### ISSUE TITLE
Error on initial showAngularStats( false );

### ISSUE THREAD

**Issue by reppners** [kentcdodds/ng-stats#48]
When calling `showAngularStats( false );` as the first interaction it fails because it early exits in `initOptions()` but later on the code relies on the opts object being initialized. So on previous version it was not necessary to do an initial `showAngularStats();` call to make it work but now it is.

**Comment by kentcdodds** [comment]
Would you mind submitting a pull request to fix this?

**Comment by reppners** [comment]
Sure, I think by tomorrow I can provide a PR.

**Comment by reppners** [comment]
@kentcdodds see #49
