### ISSUE TITLE
window.self.clearTimeout is not a function

### ISSUE THREAD

**Issue by amirgon** [kentcdodds/ng-stats#59]
When running as snippet on Chrome 51, it crashes with the following error:
```
Uncaught TypeError: window.self.clearTimeout is not a function
Uncaught TypeError: window.self.setTimeout is not a function
```
Removing `window.self.` before these functions solves the problem.

**Comment by kentcdodds** [comment]
We need to support both `window.self.clearTimeout` as well as `window.clearTimeout`. Mind making a pull request? http://makeapullrequest.com
